experiment_name: "uav_pathloss_experiments"
run_name: "msff-unet-baseline"


#training:
epochs: 1      # For test purposes only. Change it to 40 for complete training.
learning_rate: 1.0e-4
batch_size: 16
save_weights_path: "artifacts/best_unet.weights.h5"
pretrained_weights_path: "artifacts/best_tuned_model_log_distance.weights.h5"


#model:
input_shape: [128, 128, 3]
